# Generated by Django 5.2.6 on 2025-09-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_name_category_unique_category_name_ci'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_ci',
        ),
    ]
